MapColonies/discrete-layer-client

package.json
src/common/i18n/en.json
src/common/i18n/he.json
src/discrete-layer/views/discrete-layer-view.tsx
yarn.lock

datetimerange picker integrated to filters

feat(datetimepicker): integration

---

.github/workflows/Main.yaml

ci: ""
https://github.community/t/treating-warnings-as-errors-because-process-env-ci-true/18032

build(ci): making ci to false

---

src/common/components/graphql/graphql.error-presentor.tsx
src/discrete-layer/components/layer-details/entity-dialog.tsx

feat: error handling

---

package.json
src/common/i18n/en.json
src/common/i18n/he.json
src/discrete-layer/components/layer-details/entity-dialog.tsx
src/discrete-layer/models/Layer3DRecordModel.base.ts
src/discrete-layer/models/RootStore.base.ts

feat: update 3d model

---

src/__mocks-data__/search-results.mock.ts
src/common/components/grid/cell-renderer/footprint.cell-renderer.tsx
src/discrete-layer/components/best-management/best-catalog.css
src/discrete-layer/components/best-management/best-catalog.tsx
src/discrete-layer/components/best-management/best-discretes.tsx
src/discrete-layer/components/catalog-tree/icon-renderers/footprint.icon-renderer.tsx
src/discrete-layer/components/drawer-opener/drawer-opener.css
src/discrete-layer/components/drawer-opener/drawer-opener.tsx
src/discrete-layer/components/layers-results/layers-results.css
src/discrete-layer/components/layers-results/layers-results.tsx
src/discrete-layer/components/map-container/layers-footprints.tsx
src/discrete-layer/components/map-container/map-container.tsx
src/discrete-layer/models/BestRecordModel.ts
src/discrete-layer/models/Layer3DRecordModel.ts
src/discrete-layer/models/LayerRasterRecordModel.ts
src/discrete-layer/models/discreteLayersStore.ts
src/discrete-layer/views/discrete-layer-view.css
src/discrete-layer/views/discrete-layer-view.tsx

feat: best catalog

---

src/common/i18n/en.json
src/common/i18n/he.json
src/discrete-layer/components/best-management/best-catalog.css
src/discrete-layer/components/best-management/best-catalog.tsx
src/discrete-layer/components/best-management/best-edit.css
src/discrete-layer/components/best-management/best-edit.tsx
src/discrete-layer/components/best-management/best-layers-presentor.tsx
src/discrete-layer/views/discrete-layer-view.tsx

best catalog component moved inside

fix: catalog moved inside

---

src/discrete-layer/models/bestStore.ts
src/discrete-layer/views/discrete-layer-view.tsx

fix: compilation errors

---

src/common/i18n/he.json
src/discrete-layer/components/layers-results/layers-results.tsx

fix: checkbox

---

src/discrete-layer/components/best-management/best-edit.css

fix: buttons

---

src/common/i18n/en.json
src/common/i18n/he.json
src/discrete-layer/components/best-management/best-discretes.tsx

remove select all checkbox from best management

fix: remove select all checkbox from best management

---

src/discrete-layer/components/best-management/best-discretes.tsx

feat: best order behaviour

---

src/discrete-layer/views/discrete-layer-view.tsx

feat: enable editing of new best

---

src/discrete-layer/views/discrete-layer-view.tsx

fix: editing of new best

---

src/common/components/form/field-label.tsx
src/discrete-layer/components/layer-details/field-value-presentors/links.value-presentors.tsx
src/discrete-layer/components/layer-details/ingestion-fields.tsx
src/discrete-layer/components/layer-details/layer-details.tsx

feat: required fields

---

package.json
public/index.html
src/common/components/form/field-label.tsx
src/discrete-layer/components/layer-details/field-value-presentors/links.value-presentors.tsx
src/discrete-layer/components/layer-details/layer-details.tsx
src/discrete-layer/components/map-container/__snapshots__/dialog-bbox.spec.tsx.snap
src/discrete-layer/components/map-container/dialog-bbox.tsx

and fix mandatory/required  indicator

chore: bump ver 195

---

src/discrete-layer/components/best-management/best-layers-presentor.tsx
src/discrete-layer/components/helpers/layersUtils.ts
src/discrete-layer/components/map-container/selected-layers-container.tsx

Start implementing rect feature.

feat: implement layers rectangles

---

src/discrete-layer/components/dialogs/file-picker-dialog.tsx

feat: file-picker auto select single mount dir

---

src/common/helpers/group-by.ts
src/discrete-layer/components/best-management/best-catalog.tsx
src/discrete-layer/components/catalog-tree/catalog-tree.tsx

Alter groupBy function to accept { name: string, predicate: (val: any) => string } instead of just string[].
fixed the problem with array values as grouping param.

fix: group by function

---

confd/production.tmpl
src/common/components/form/tooltipped.value.tsx
src/common/i18n/he.json
src/discrete-layer/components/layer-details/layer-details.css
src/discrete-layer/views/components/details-panel.component.css

fix: details panel font and tooltip

fix: details panel font and tooltip

---

src/common/components/auto-direction-box/auto-direction-box.component.tsx
src/common/components/error/error-presentor.css
src/common/components/error/graphql.error-presentor.tsx
src/common/components/form/tooltipped.value.tsx
src/common/components/grid/cell-renderer/details-expander.cell-renderer.css
src/common/components/tree/renderers/node-content-renderer.tsx
src/common/hooks/debounce-field.hook.ts
src/common/i18n/en.json
src/common/i18n/he.json
src/discrete-layer/components/export-layer/export-layer-footer.component.tsx
src/discrete-layer/components/map-container/catalogFilter/catalog-filter-panel.component.tsx
src/discrete-layer/components/map-container/polygon-selection-ui_2.tsx
src/discrete-layer/components/system-status/cell-renderer/job-details.cell-renderer.css
src/discrete-layer/views/components/details-panel.component.tsx

**bugs fixed**
MAPCO-3538
- Export layer server error not presenting, related to MAPCO-3251
- Job manager details panel sometimes not opens.
- Catalog, Reduce unnecessary tooltips.
- Catalog filters close panel of reset filters.
- GraphQL errors component direction

fix: v2.1.1 bugs and improvements

---

src/common/components/error/error-presentor.css

fix: error list direction

---

helm/config/default.conf
src/discrete-layer/components/layer-details/field-value-presentors/lookup.options-presentor.tsx
src/discrete-layer/components/layer-details/field-value-presentors/resolution.value-presentor.tsx

Using the right value in order to reset select fields in dialog

Reset select fields

---

src/discrete-layer/components/layer-details/field-value-presentors/json.value-presentor.tsx

Sent e.target to formik handleChange and handleBlur

Handle geographical delimitation formik handleChange and handleBlur better

---

src/discrete-layer/components/layer-details/entity.dialog.tsx
src/discrete-layer/components/layer-details/layer-datails-form.tsx

fix: delete typename from metadata.recordModel ( MAPCO-6053 )

---

src/discrete-layer/components/layer-details/raster/entity.raster.dialog.tsx

fix: use useEffect to trigger ingestQueries only when submitting form ( MAPCO-6199 )

---

CHANGELOG.md
confd/production.tmpl
helm/Chart.yaml
package.json
src/discrete-layer/components/layer-details/raster/pp-extent-vector-layer.tsx
src/discrete-layer/models/RootStore.base.ts

Polygon parts by WFS lazy loading

feat: pp wfs pagination ( MAPCO-6827 )
